package com.learning.database.inheritance.repository;

import com.learning.database.inheritance.entity.ComputerEntity;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ComputerRepository extends JpaRepository<ComputerEntity, Long> {

    /**
     * Finds all {@link ComputerEntity} records matching the given operating system.
     * Derived query generated by Spring Data JPA from the method name (equivalent to
     * {@code WHERE os = :os}).
     * <p>
     * Note: this repository uses the {@code MappedSuperclass} inheritance strategy, so no
     * polymorphic queries are possible — each concrete entity has its own dedicated repository.
     *
     * @param os the operating system value to match
     * @return list of {@link ComputerEntity} instances with the given operating system
     */
    List<ComputerEntity> findByOs(String os);
}
